import "./globals.css";
import Header from "./components/layout/Header";

export const metadata = {
  title: "Next App Todo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="p-4 sm:px-8">{children}</main>
      </body>
    </html>
  );
}
